### ISSUE TITLE
Add support for N opcode

### ISSUE THREAD

**Issue by holtgrewe** [GregoryFaust/samblaster#10]
I think this could be supported by simply using `else if (opCode == 'D' || opcode == 'N')` instead of `else if (opCode == 'D')` in line 647 of `samblaster.cpp`.

What do you think?

**Comment by GregoryFaust** [comment]
I believe this is correct, but I personally am not aware of an aligner other than BLAT that outputs Ns in CIGAR strings.  Do you have a use case in mind?

Thanks,
Greg

**Comment by holtgrewe** [comment]
The RNA-seq STAR aligner writes this to the resulting SAM file.

**Comment by GregoryFaust** [comment]
Ok, I will fix this at the same time as I fix issue #11, as they both involve the same chunk of code.

Greg

**Comment by schelhorn** [comment]
In general, all splicing-aware (RNA-Seq) aligners do that. It's highly relevant. It's also part of the [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf) (see table on page 5).

**Comment by GregoryFaust** [comment]
Fixed in release 0.1.22.
