### ISSUE TITLE
Mate tags

### ISSUE THREAD

**Issue by cc2qe** [GregoryFaust/samblaster#12]
Hey Greg,

I'm having an issue running Samblaster with "addMateTags" on long, 250 bp reads. It shows the following error and then dies partway through the file.
```
samblaster: New buffer length exceeds maximum while adding Mate tags.
```

Seems like it might be because the CIGAR string is longer than the number of bytes allocated for that field. Would it be easy to fix this? I can provide an example BAM if needed.

**Comment by GregoryFaust** [comment]
Fixed in release 0.1.22.
