### ISSUE TITLE
Write duplication metrics to file

### ISSUE THREAD

**Issue by dakl** [GregoryFaust/samblaster#16]
Thanks for a great tool! 

It would be nice if it was possible to write the output metrics to a separate file like so: 

``` bash
bwa mem -M <idxbase> samp.r1.fq samp.r2.fq | samblaster -M -m metrics.txt | samtools view -Sb - > samp.out.bam
```

The new part being `-m metrics.txt`. A structured format would be nice, tsv probably easiest to parse downstream. 

Current output to stderr: `samblaster: Removed 1229 of 4596 (26.74%) read ids as duplicates using 1324k memory in 0.000S CPU seconds and 0S wall time.
`. My suggestion would be something like this: 

```
TOTAL_READS   DUPLICATES_REMOVED   MEMORY_USED   CPU_SECONDS   WALL_TIME
4596          1229                 1324k         0.000         0
```

**Comment by dakl** [comment]
I've made a patch in #17.

**Comment by GregoryFaust** [comment]
*samblaster* version 0.1.25 now outputs many more statistics about the category of reads in the input file and the duplicates in each category, albeit still to **stderr**.
