### ISSUE TITLE
after extracting disc and split reads, does the final bam still contain them?

### ISSUE THREAD

**Issue by crazyhottommy** [GregoryFaust/samblaster#18]
`bwa mem <idxbase> samp.r1.fq samp.r2.fq | samblaster -e -d samp.disc.sam -s samp.split.sam | samtools view -Sb - > samp.out.bam`  

Does samp.out.bam still contain the discordants and split reads?

Thanks,
Ming

**Comment by vyx-greg-faust** [comment]
Absolutely. The "side" extraction of discordants, split reads, and/or the unmapped/clipped reads does not impact the contents of the <out.bam> file in any way.

**Comment by GregoryFaust** [comment]
Absolutely. The "side" extraction of discordants, split reads, and/or the unmapped/clipped reads does not impact the contents of the file in any way.
