### ISSUE TITLE
More info for missing pair

### ISSUE THREAD

**Issue by zeeev** [GregoryFaust/samblaster#22]
@GregoryFaust ,

I'm trying to track down a problem with grouping reads.  The error I get:

`samblaster: Can't find first and/or second of pair in sam block of length 1 for id: xxxxx`

It would be exceptionally helpful if the error reported the chromosome and position of the read so they could be quickly pulled for examination. 

Thank you.

**Comment by GregoryFaust** [comment]
Closed in release 0.1.23

**Comment by jiadong324** [comment]
@GregoryFaust 
Dear author,

I have the same issue here. But what do you mean by "Closed in release 0.1.23"?
I am using 0.1.23 right now. And I am using "samtools sort -n" command to sort bwa aligned reads in a SAM file.

What do you think of it? Thanks in advance!

**Comment by vyx-greg-faust** [comment]
By "Closed in 0.1.23" I mean that I included the requested additional information into the error message for missing mate, namely the chromosome and position of the read that produced the error.

Yes, "samtools sort -n -O SAM" or "sambamba sort -n -u -o /dev/stdout | sambamba view -f sam -h" will work to sort output from bwa or any other paired-end read aligner in a way that *samblaster* can use.

**Comment by jiadong324** [comment]
@vyx-greg-faust Thanks for your explanation and instructions.
