### ISSUE TITLE
Plans to use htslib ?

### ISSUE THREAD

**Issue by tseemann** [GregoryFaust/samblaster#25]
Greg,

Do you have any plans to incorporate `htslib` into `samblaster`?
https://github.com/samtools/htslib

Torsten

**Comment by vyx-greg-faust** [comment]
I don't at the moment, as the normal use of *samblaster* is to pipe the output of the aligner straight through *samblaster* before the SAM format is converted to BAM or CRAM. In addition, most stored BAM and CRAM files are stored in position sort order as that is what most other tools such as GATK expect as input. See here for an example: [GATK Input Requirements](http://gatkforums.broadinstitute.org/wdl/discussion/1204/what-input-files-does-the-gatk-accept-require). Yet *samblaster* requires the input to be read-id grouped as it is when first produced by the aligner.

Having said all this, if there is enough call for this feature, I will reconsider.

Thanks,
Greg

**Comment by tseemann** [comment]
I just thought it might make SAM parsing and editing faster and more reliable. You are doing a lot of string munging and it may be easier to maintain. But as you said, it is a very niche use case and is a nice fast pipe component so there may be no need to complicate things :)

Thanks for answering!
