### ISSUE TITLE
Very different result between samtools and samblaster

### ISSUE THREAD

**Issue by biozzq** [GregoryFaust/samblaster#46]
Dear @GregoryFaust 

I am using Lumpy to detect CNV. During preparing the discordant paired-end alignments, I found that the results from the following two pipelines are very different. In my test, the samblaster just reported 0 discordant read pair, but samtools reported many.

(1) samtools view -b -F 1294 sample.bam #refer to the github of lumpy (https://github.com/arq5x/lumpy-sv)
(2) samtools sort -@ 4 -O SAM -n sample.bam | samblaster (Version.0.1.25) -a -e -d $prefix.disc.sam -s $prefix.split.sam -o /dev/null

Hope you can help me, thank you.

Sincerely,
Zheng Zhuqing

**Comment by GregoryFaust** [comment]
Thanks for bringing this to my attention. Somehow, *samblaster* V25 does NOT output discordants when used with the **acceptDupMarks**(**-a**) option. I have a fix already prepared which I am now testing and will release very soon (this week at latest). In the mean time, *samblaster* V24 will work for the pipeline you have shown.

As an aside, if your BAM file was aligned with **BWA MEM**, both of your pipeline fragments shown assume that the **-M** option was not used. If it was, you will need to use the **-M** option with *samblaster* or make a change to the **samtools** filter specification. 

Thanks again.
Greg

**Comment by biozzq** [comment]
Dear @GregoryFaust 

Thank you for reminding. Also I look forward to your update.

Sincerely,
Zhuqing

**Comment by GregoryFaust** [comment]
Closed in v.0.1.26
