### ISSUE TITLE
Support for BED files?

### ISSUE THREAD

**Issue by samhunter** [GregoryFaust/samblaster#9]
I don't see anything in the documentation about support for applying Samblaster to specific regions of a genome using something like a BED file. Is this a feature that could be integrated easily?

**Comment by GregoryFaust** [comment]
Could you please tell me a little bit about the usage scenario you have in mind?  I am unclear why this would be a useful feature for marking duplicates.  But I do see why this might be useful in the case in which you are using the --accept-dups option and just want to pull out the split reads and/or discordant reads within a range.  Of course in that case, one could use samtools view -L to subset those sam files with a bed file after they are produced by samblaster.

**Comment by samhunter** [comment]
Hey Gergory, yes primarily from the split/discordant reads angle, but your point about samtools is well taken, thanks.

Sam
